persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

listener 1883
protocol mqtt

# Authentication
allow_anonymous false
password_file /mosquitto/config/passwd

# Security
max_connections -1
max_inflight_messages 20
max_queued_messages 1000
