version: '3.8'

services:
  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    container_name: ntfy
    volumes:
      - ./config/ntfy/server.yml:/etc/ntfy/server.yml
      - ./data/ntfy/cache.db:/var/cache/ntfy/cache.db
      - ./data/ntfy/user.db:/var/lib/ntfy/user.db
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "8080:80"
    restart: unless-stopped

  gotify:
    image: gotify/server:2.5.0
    container_name: gotify
    ports:
      - "8081:80"
    restart: unless-stopped