#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# fix-dns-port.sh — 解决 systemd-resolved 占用 53 端口问题
#
# 用法:
#   ./scripts/fix-dns-port.sh --check   # 检查当前状态
#   ./scripts/fix-dns-port.sh --apply   # 应用修复 (禁用 systemd-resolved)
#   ./scripts/fix-dns-port.sh --restore # 恢复 systemd-resolved
#
# 说明:
#  - 大多数 Linux 发行版使用 systemd-resolved 监听 53 端口
#  - AdGuard Home 也需要 53 端口，需要先禁用 systemd-resolved
# ═══════════════════════════════════════════════════════════════════════════

set -euo pipefail

# 颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

MODE="check"
SYSTEMD_RESOLVED_CONF="/etc/systemd/resolved.conf"
RESOLV_CONF="/etc/resolv.conf"
BACKUP_SUFFIX=".backup.$(date +%Y%m%d-%H%M%S)"

# ═══════════════════════════════════════════════════════════════════════════

show_help() {
  cat <<EOF
DNS 端口冲突修复工具 — 处理 systemd-resolved 占用 53 端口问题

用法: $0 [OPTIONS]

选项:
  --check   检查当前 DNS 状态 (默认)
  --apply   应用修复 (禁用 systemd-resolved)
  --restore 恢复 systemd-resolved 到原始状态
  --help    显示此帮助

示例:
  $0 --check   # 查看当前配置
  $0 --apply   # 执行修复 (需要 sudo)
  $0 --restore # 恢复

注意:
  - 该脚本需要 root 权限修改系统配置
  - 修复后需要重启 systemd-resolved 或 reboot
  - 建议在部署 AdGuard 之前执行

EOF
  exit 0
}

# ═══════════════════════════════════════════════════════════════════════════

check_status() {
  echo "检查 DNS 配置状态..."
  echo

  # 1. 检查 systemd-resolved 是否运行
  if systemctl is-active --quiet systemd-resolved; then
    echo -e "  ${YELLOW}⚠️  systemd-resolved 正在运行${NC}"
    systemctl status systemd-resolved --no-pager -l
  else
    echo -e "  ${GREEN}✓ systemd-resolved 未运行${NC}"
  fi

  echo

  # 2. 检查谁在监听 53 端口
  echo "检查 53 端口占用:"
  if ss -tuln | grep -q ':53 '; then
    echo -e "  ${RED}✗ 53 端口已被占用:${NC}"
    ss -tuln | grep ':53 '
  else
    echo -e "  ${GREEN}✓ 53 端口空闲${NC}"
  fi

  echo

  # 3. 检查 /etc/resolv.conf
  echo "检查 resolv.conf:"
  if [[ -L "$RESOLV_CONF" ]]; then
    local target=$(readlink "$RESOLV_CONF")
    echo "  $RESOLV_CONF -> $target"
    if [[ "$target" == "/run/systemd/resolve/stub-resolv.conf" ]]; then
      echo -e "  ${YELLOW}⚠️  指向 systemd-resolved (会占用 53 端口)${NC}"
    elif [[ "$target" == "/run/systemd/resolve/resolv.conf" ]]; then
      echo -e "  ${GREEN}✓ 指向实际 DNS 配置 (不占用 53 端口)${NC}"
    fi
  else
    echo "  $RESOLV_CONF 是普通文件 (非符号链接)"
    cat "$RESOLV_CONF" 2>/dev/null || echo "  (无法读取)"
  fi

  echo

  # 4. 检查 systemd-resolved 配置
  echo "检查 $SYSTEMD_RESOLVED_CONF:"
  if [[ -f "$SYSTEMD_RESOLVED_CONF" ]]; then
    local dnsstublistener=$(grep -E '^DNSStubListener=' "$SYSTEMD_RESOLVED_CONF" | cut -d= -f2)
    case "$dnsstublistener" in
      "yes")
        echo -e "  ${YELLOW}⚠️  DNSStubListener=yes (会占用 53 端口)${NC}"
        ;;
      "no")
        echo -e "  ${GREEN}✓ DNSStubListener=no (不会占用 53 端口)${NC}"
        ;;
      "")
        echo "  DNSStubListener 未设置 (默认 yes)"
        ;;
    esac
  else
    echo "  配置文件不存在"
  fi

  echo
  echo "────────────────────────────────────────────────────────────────────────────────────────────"
  echo

  # 5. 给出建议
  if ss -tuln | grep -q ':53 ' && systemctl is-active --quiet systemd-resolved; then
    echo -e "${YELLOW}⚠️  检测到 53 端口被 systemd-resolved 占用，AdGuard 将无法启动。${NC}"
    echo "建议: 运行 '$0 --apply' 禁用 systemd-resolved"
    return 1
  else
    echo -e "${GREEN}✅ 53 端口可用，无需修复${NC}"
    return 0
  fi
}

# ═══════════════════════════════════════════════════════════════════════════

apply_fix() {
  echo "应用修复..."

  # 检查权限
  if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}❌ 需要 root 权限${NC}"
    echo "请使用: sudo $0 --apply"
    exit 1
  fi

  # 1. 备份原始配置
  echo "备份配置文件..."
  cp "$SYSTEMD_RESOLVED_CONF" "${SYSTEMD_RESOLVED_CONF}${BACKUP_SUFFIX}" 2>/dev/null || true
  cp "$RESOLV_CONF" "${RESOLV_CONF}${BACKUP_SUFFIX}" 2>/dev/null || true
  echo -e "  ${GREEN}✓ 备份完成${NC}"

  # 2. 修改 systemd-resolved 配置
  echo "配置 systemd-resolved..."
  if [[ -f "$SYSTEMD_RESOLVED_CONF" ]]; then
    # 设置 DNSStubListener=no
    if grep -q '^DNSStubListener=' "$SYSTEMD_RESOLVED_CONF"; then
      sed -i 's/^DNSStubListener=.*/DNSStubListener=no/' "$SYSTEMD_RESOLVED_CONF"
    else
      echo "DNSStubListener=no" >> "$SYSTEMD_RESOLVED_CONF"
    fi
    echo -e "  ${GREEN}✓ 设置 DNSStubListener=no${NC}"
  else
    echo "  ${YELLOW}⚠️  $SYSTEMD_RESOLVED_CONF 不存在，跳过${NC}"
  fi

  # 3. 修改 resolv.conf 指向实际配置
  echo "配置 resolv.conf..."
  if [[ -L "$RESOLV_CONF" ]]; then
    # 当前是 symlink，修改指向
    rm "$RESOLV_CONF"
  fi
  # 写入静态 DNS (可选: 使用 127.0.0.1 指向 AdGuard)
  cat > "$RESOLV_CONF" <<EOF
# Generated by fix-dns-port.sh
nameserver 127.0.0.1
options timeout:2 attempts:3
EOF
  echo -e "  ${GREEN}✓ resolv.conf 已更新 (nameserver 127.0.0.1)${NC}"

  # 4. 重启 systemd-resolved
  echo "重启 systemd-resolved..."
  if systemctl restart systemd-resolved; then
    echo -e "  ${GREEN}✓ systemd-resolved 已重启${NC}"
  else
    echo -e "  ${YELLOW}⚠️  systemd-resolved 重启失败 (可能需要手动)${NC}"
  fi

  # 5. 停止并禁用 systemd-resolved (可选, 如果完全不需要)
  read -rp "是否完全禁用 systemd-resolved? (推荐: n) [y/N]: " disable_svc
  if [[ "$disable_svc" =~ ^[Yy]$ ]]; then
    systemctl stop systemd-resolved
    systemctl disable systemd-resolved
    echo -e "  ${GREEN}✓ systemd-resolved 已停止并禁用${NC}"
  fi

  echo
  echo -e "${GREEN}✅ 修复完成！${NC}"
  echo
  echo "下一步:"
  echo "  1. 验证 53 端口空闲: ss -tuln | grep :53"
  echo "  2. 启动 AdGuard: docker compose up -d adguard"
  echo "  3. 测试 DNS: dig @127.0.0.1 google.com"
  echo
  echo "如需恢复: sudo $0 --restore"
}

# ═══════════════════════════════════════════════════════════════════════════

restore_fix() {
  echo "恢复原始配置..."

  if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}❌ 需要 root 权限${NC}"
    echo "请使用: sudo $0 --restore"
    exit 1
  fi

  # 1. 恢复 systemd-resolved 配置
  if [[ -f "${SYSTEMD_RESOLVED_CONF}${BACKUP_SUFFIX}" ]]; then
    cp "${SYSTEMD_RESOLVED_CONF}${BACKUP_SUFFIX}" "$SYSTEMD_RESOLVED_CONF"
    echo -e "  ${GREEN}✓ 恢复 $SYSTEMD_RESOLVED_CONF${NC}"
  fi

  # 2. 恢复 resolv.conf
  if [[ -f "${RESOLV_CONF}${BACKUP_SUFFIX}" ]]; then
    cp "${RESOLV_CONF}${BACKUP_SUFFIX}" "$RESOLV_CONF"
    echo -e "  ${GREEN}✓ 恢复 $RESOLV_CONF${NC}"
  fi

  # 3. 重启 systemd-resolved
  if systemctl restart systemd-resolved; then
    echo -e "  ${GREEN}✓ systemd-resolved 已重启${NC}"
  fi

  # 4. 重新启用 (如果之前禁用了)
  if systemctl is-enabled --quiet systemd-resolved 2>/dev/null; then
    :
  else
    systemctl enable systemd-resolved 2>/dev/null || true
    systemctl start systemd-resolved 2>/dev/null || true
    echo -e "  ${GREEN}✓ systemd-resolved 已重新启用${NC}"
  fi

  echo
  echo -e "${GREEN}✅ 恢复完成！${NC}"
  echo "systemd-resolved 现在应该占用 53 端口。"
}

# ═══════════════════════════════════════════════════════════════════════════

main() {
  case "${1:-}" in
    --apply)
      MODE="apply"
      ;;
    --restore)
      MODE="restore"
      ;;
    --check|"")
      MODE="check"
      ;;
    --help|-h)
      show_help
      ;;
    *)
      echo "未知选项: $1"
      show_help
      exit 1
      ;;
  esac

  case "$MODE" in
    check) check_status ;;
    apply) apply_fix ;;
    restore) restore_fix ;;
  esac
}

main "$@"