#!/bin/bash
# =============================================================================
# fix-dns-port.sh — Fix systemd-resolved DNS port 53 conflict
#
# AdGuard Home needs port 53. systemd-resolved often occupies it.
# This script detects and resolves the conflict.
#
# Usage:
#   ./fix-dns-port.sh --check   # Check if port 53 is in use
#   ./fix-dns-port.sh --apply  # Apply the fix (disable systemd-resolved)
#   ./fix-dns-port.sh --restore # Restore systemd-resolved (undo fix)
#
# Requirements: root (sudo)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

check_port() {
    echo -e "${YELLOW}Checking port 53 status...${NC}"
    if ss -tuln | grep -q ':53 '; then
        echo -e "${RED}Port 53 is OCCUPIED${NC}"
        echo -e "Detected processes on port 53:"
        ss -tuln | grep ':53 '
        echo ""
        echo -e "${YELLOW}Most likely cause: systemd-resolved${NC}"
        if resolvectl status 2>/dev/null | grep -q 'DNS Stub Listener'; then
            echo "systemd-resolved DNS stub listener is active."
        fi
        return 1
    else
        echo -e "${GREEN}Port 53 is FREE${NC}"
        return 0
    fi
}

apply_fix() {
    echo -e "${YELLOW}Applying fix for port 53 conflict...${NC}"

    # Check if systemd-resolved
    if ! systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        echo -e "${GREEN}systemd-resolved is not running. No fix needed.${NC}"
        return 0
    fi

    echo -e "${YELLOW}Stopping systemd-resolved...${NC}"
    sudo systemctl stop systemd-resolved
    echo -e "${GREEN}Stopped systemd-resolved${NC}"

    # Backup and remove the symlink
    if [ -L /etc/resolv.conf ]; then
        echo -e "${YELLOW}Backing up existing /etc/resolv.conf...${NC}"
        sudo mv /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d%H%M%S)
    fi

    # Create new resolv.conf with common DNS servers
    echo -e "${YELLOW}Creating /etc/resolv.conf...${NC}"
    sudo tee /etc/resolv.conf > /dev/null << 'EOF'
# Generated by fix-dns-port.sh
# If you restore systemd-resolved, restore from /etc/resolv.conf.backup.*
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 2001:4860:4860::8888
EOF

    echo -e "${GREEN}Disabled systemd-resolved. Port 53 is now available.${NC}"
    echo -e "${YELLOW}NOTE: System DNS is now managed manually.${NC}"
    echo -e "To restore: sudo ./fix-dns-port.sh --restore"
}

restore() {
    echo -e "${YELLOW}Restoring systemd-resolved...${NC}"

    # Remove manual resolv.conf
    if [ -f /etc/resolv.conf ]; then
        sudo rm /etc/resolv.conf
    fi

    # Restore backup if exists
    BACKUP=$(ls -t /etc/resolv.conf.backup.* 2>/dev/null | head -1)
    if [ -n "$BACKUP" ]; then
        echo -e "Restoring $BACKUP"
        sudo mv "$BACKUP" /etc/resolv.conf
    else
        echo -e "Creating new /etc/resolv.conf symlink for systemd-resolved"
        sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
    fi

    sudo systemctl start systemd-resolved
    echo -e "${GREEN}systemd-resolved restored.${NC}"
}

case "${1:-}" in
    --check)
        check_port
        ;;
    --apply)
        apply_fix
        ;;
    --restore)
        restore
        ;;
    *)
        echo "Usage: $0 {--check|--apply|--restore}"
        echo "  --check   Check if port 53 is available"
        echo "  --apply   Fix port 53 conflict (disable systemd-resolved)"
        echo "  --restore Restore systemd-resolved (undo fix)"
        exit 1
        ;;
esac
