#!/bin/bash

# Home Automation Stack Setup Script
# Sets up Home Assistant, Zigbee2MQTT, Mosquitto, and Node-RED

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

print_status() { echo -e "${GREEN}[+]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[!]${NC} $1"; }
print_error() { echo -e "${RED}[-]${NC} $1"; }

check_prerequisites() {
    print_status "Checking prerequisites..."
    command -v docker >/dev/null 2>&1 || { print_error "Docker required"; exit 1; }
    
    if command -v docker-compose >/dev/null; then
        DOCKER_COMPOSE_CMD="docker-compose"
    elif docker compose version >/dev/null 2>&1; then
        DOCKER_COMPOSE_CMD="docker compose"
    else
        print_error "Docker Compose required"; exit 1
    fi
    
    # Check for USB devices if needed
    if [ -n "${ZIGBEE2MQTT_PORT}" ] && [ "${ZIGBEE2MQTT_PORT}" != "auto" ]; then
        if [ ! -e "${ZIGBEE2MQTT_PORT}" ]; then
            print_warning "Zigbee adapter not found at ${ZIGBEE2MQTT_PORT}"
            print_warning "You may need to configure the correct device path"
        fi
    fi
}

setup_directories() {
    print_status "Setting up directories..."
    
    mkdir -p "$PROJECT_ROOT"/data/{homeassistant,zigbee2mqtt,mosquitto/{config,data,log},nodered/data,esphome,appdaemon/{conf,apps}}
    mkdir -p "$PROJECT_ROOT"/config/{zigbee2mqtt,mosquitto,nodered,homeassistant/{packages,automations,scripts}}
    mkdir -p "$PROJECT_ROOT"/logs
    
    # Set permissions
    chmod -R 755 "$PROJECT_ROOT"/config
    chmod -R 755 "$PROJECT_ROOT"/data
    
    print_status "Directories created successfully."
}

generate_configs() {
    print_status "Generating configuration files..."
    
    # Zigbee2MQTT configuration
    cat > "$PROJECT_ROOT/config/zigbee2mqtt/configuration.yaml" << 'EOF'
# Zigbee2MQTT configuration
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  user: homeassistant
  password: changeme
serial:
  port: /dev/ttyUSB0
  adapter: znp
frontend:
  port: 8080
  host: 0.0.0.0
advanced:
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  channel: 11
  pan_id: 0x1a62
  extended_pan_id: [0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]
device_options: {}
device_options_string: {}
blocklist: []
passlist: []
queue: {}
EOF
    
    # MQTT password file (will be generated by setup)
    cat > "$PROJECT_ROOT/config/mosquitto/passwd" << 'EOF'
# MQTT users and passwords
# Format: username:password
# Use mosquitto_passwd to generate: mosquitto_passwd -c passwd username
homeassistant:$7$101$W6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq==
zigbee2mqtt:$7$101$W6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq6qBq==
EOF
    
    # MQTT ACL file
    cat > "$PROJECT_ROOT/config/mosquitto/acl" << 'EOF'
# MQTT Access Control List
user homeassistant
topic readwrite #

user zigbee2mqtt
topic readwrite zigbee2mqtt/#
topic readwrite home/#

# Anonymous read-only access (optional)
# pattern read $SYS/#
EOF
    
    # Home Assistant minimal configuration
    cat > "$PROJECT_ROOT/config/homeassistant/configuration.yaml" << 'EOF'
# Home Assistant configuration
default_config:

# Include packages
homeassistant:
  packages: !include_dir_named packages/

# MQTT integration
mqtt:
  broker: mosquitto
  port: 1883
  username: homeassistant
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# Zigbee2MQTT integration
zeroconf:

# Frontend
frontend:

# Automation
automation: !include automations.yaml
script: !include scripts.yaml

# Logging
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug

# Secrets (create secrets.yaml)
# secrets: !include secrets.yaml
EOF
    
    # Create empty automation and script files
    touch "$PROJECT_ROOT/config/homeassistant/automations.yaml"
    touch "$PROJECT_ROOT/config/homeassistant/scripts.yaml"
    
    # Create secrets template
    cat > "$PROJECT_ROOT/config/homeassistant/secrets.yaml" << 'EOF'
# Home Assistant Secrets
# Fill in your actual secrets here

# MQTT
mqtt_password: changeme_CHANGE_IN_PRODUCTION

# API keys
openweathermap_api_key: YOUR_API_KEY
google_calendar_client_id: YOUR_CLIENT_ID
google_calendar_client_secret: YOUR_CLIENT_SECRET

# Other integrations
spotify_client_id: YOUR_CLIENT_ID
spotify_client_secret: YOUR_CLIENT_SECRET
EOF
    
    print_status "Configuration files generated."
}

setup_mqtt_auth() {
    print_status "Setting up MQTT authentication..."
    
    # This would typically use mosquitto_passwd, but we're using a template
    print_warning "Using pre-generated password hash. Change in production!"
    print_warning "To generate proper passwords, install mosquitto and run:"
    print_warning "  mosquitto_passwd -b config/mosquitto/passwd username password"
}

start_services() {
    print_status "Starting Home Automation Stack..."
    
    cd "$PROJECT_ROOT"
    
    # Load environment variables
    if [ -f .env.home-automation ]; then
        export $(grep -v '^#' .env.home-automation | xargs)
    fi
    
    # Start core services
    $DOCKER_COMPOSE_CMD -f docker-compose.home-automation.yml up -d \
        homeassistant \
        zigbee2mqtt \
        mosquitto \
        nodered
    
    print_status "Waiting for services to start..."
    sleep 30
    
    # Check service status
    check_service_health
    
    print_status "Core services started successfully!"
}

check_service_health() {
    print_status "Checking service health..."
    
    local services=("homeassistant" "zigbee2mqtt" "mosquitto" "nodered")
    local all_healthy=true
    
    for service in "${services[@]}"; do
        if docker ps --filter "name=$service" --format "{{.Status}}" | grep -q "Up"; then
            print_status "$service: Running"
        else
            print_warning "$service: Not running (check logs with 'docker logs $service')"
            all_healthy=false
        fi
    done
    
    if $all_healthy; then
        print_status "All core services are running!"
    else
        print_warning "Some services may need attention. Check logs for details."
    fi
}

display_access_info() {
    local ip=$(hostname -I | awk '{print $1}')
    
    cat << EOF

=== Home Automation Stack Installation Complete ===

Services:
- Home Assistant: http://$ip:8123
- Zigbee2MQTT: http://$ip:8080
- Node-RED: http://$ip:1880
- MQTT Broker: $ip:1883

Configuration Files:
- Home Assistant: $PROJECT_ROOT/config/homeassistant/
- Zigbee2MQTT: $PROJECT_ROOT/config/zigbee2mqtt/
- Mosquitto: $PROJECT_ROOT/config/mosquitto/
- Node-RED: $PROJECT_ROOT/config/nodered/

Data Storage:
- All data stored in: $PROJECT_ROOT/data/

Next Steps:
1. Access Home Assistant at http://$ip:8123
2. Complete the initial setup wizard
3. Change all default passwords in .env.home-automation
4. Configure Zigbee adapter permissions if needed
5. Set up automations and integrations
6. Add your smart devices

Troubleshooting:
- Check logs: cd $PROJECT_ROOT && $DOCKER_COMPOSE_CMD -f docker-compose.home-automation.yml logs -f
- Restart services: cd $PROJECT_ROOT && $DOCKER_COMPOSE_CMD -f docker-compose.home-automation.yml restart
- Stop services: cd $PROJECT_ROOT && $DOCKER_COMPOSE_CMD -f docker-compose.home-automation.yml down

Optional Services:
- ESPHome: http://$ip:6052 (if enabled)
- AppDaemon: http://$ip:5050 (if enabled)
- Grafana: http://$ip:3001 (if enabled)
- Prometheus: http://$ip:9090 (if enabled)

EOF
}

main() {
    print_status "Starting Home Automation Stack Setup"
    echo ""
    
    check_prerequisites
    setup_directories
    generate_configs
    setup_mqtt_auth
    start_services
    display_access_info
    
    print_status "Setup complete!"
    print_status "Remember to change all default passwords before production use."
}

main "$@"