#!/usr/bin/env bash
# ==============================================================================
# HomeLab Stack — Test Report Functions
# Generates test reports in terminal and JSON formats
# ==============================================================================

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

# Print test summary
print_summary() {
    local passed="$1" failed="$2" skipped="$3" duration="$4"
    
    echo ""
    echo -e "${BOLD}──────────────────────────────────────${NC}"
    echo -e "Results: ${GREEN}$passed passed${NC}, ${RED}$failed failed${NC}, ${YELLOW}$skipped skipped${NC}"
    echo -e "Duration: ${duration}s"
    echo -e "${BOLD}──────────────────────────────────────${NC}"
}

# Write JSON report
write_json_report() {
    local passed="$1" failed="$2" skipped="$3" duration="$4"
    local report_dir="$(dirname "$0")/../results"
    local report_file="$report_dir/report.json"
    
    mkdir -p "$report_dir"
    
    cat > "$report_file" << EOF
{
  "timestamp": "$(date -Iseconds)",
  "duration_seconds": $duration,
  "summary": {
    "passed": $passed,
    "failed": $failed,
    "skipped": $skipped,
    "total": $((passed + failed + skipped))
  },
  "status": "$([ "$failed" -eq 0 ] && echo 'passed' || echo 'failed')",
  "environment": {
    "hostname": "$(hostname)",
    "docker_version": "$(docker --version 2>/dev/null | cut -d' ' -f3 | tr -d ',')"
  }
}
EOF
    
    echo "JSON report written to: $report_file"
}

# Print test result line
print_result() {
    local status="$1" message="$2" duration="${3:-}"
    local icon=""
    
    case "$status" in
        pass) icon="${GREEN}✓ PASS${NC}" ;;
        fail) icon="${RED}✗ FAIL${NC}" ;;
        skip) icon="${YELLOW}⊘ SKIP${NC}" ;;
    esac
    
    if [[ -n "$duration" ]]; then
        echo -e "  $icon $message (${duration}s)"
    else
        echo -e "  $icon $message"
    fi
}

# Generate JUnit XML report (for CI)
write_junit_report() {
    local output_file="$1"
    shift
    local test_suites=("$@")
    
    local total_tests=0
    local total_failures=0
    local total_time=0
    
    # Calculate totals
    for suite in "${test_suites[@]}"; do
        IFS='|' read -r name tests failures time <<< "$suite"
        total_tests=$((total_tests + tests))
        total_failures=$((total_failures + failures))
        total_time=$(echo "$total_time + $time" | bc)
    done
    
    cat > "$output_file" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="$total_tests" failures="$total_failures" time="$total_time">
EOF
    
    for suite in "${test_suites[@]}"; do
        IFS='|' read -r name tests failures time <<< "$suite"
        cat >> "$output_file" << EOF
  <testsuite name="$name" tests="$tests" failures="$failures" time="$time">
  </testsuite>
EOF
    done
    
    echo "</testsuites>" >> "$output_file"
}

# Create markdown report
write_markdown_report() {
    local output_file="$1"
    local passed="$2" failed="$3" skipped="$4" duration="$5"
    
    cat > "$output_file" << EOF
# HomeLab Stack — Test Report

**Generated:** $(date)

## Summary

| Status | Count |
|--------|-------|
| ✅ Passed | $passed |
| ❌ Failed | $failed |
| ⊘ Skipped | $skipped |
| **Total** | $((passed + failed + skipped)) |

**Duration:** ${duration}s

## Status

$([ "$failed" -eq 0 ] && echo '✅ All tests passed!' || echo '❌ Some tests failed')

---
*Generated by HomeLab Stack Test Framework*
EOF
}