version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.3.12
    container_name: ollama
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}
      - ROCM_VISIBLE_DEVICES=${ROCM_VISIBLE_DEVICES:-}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.3.32
    container_name: open-webui
    ports:
      - "3000:3000"
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}
      - ROCM_VISIBLE_DEVICES=${ROCM_VISIBLE_DEVICES:-}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  stable-diffusion:
    image: universonic/stable-diffusion-webui:latest-sha
    container_name: stable-diffusion
    ports:
      - "7860:7860"
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}
      - ROCM_VISIBLE_DEVICES=${ROCM_VISIBLE_DEVICES:-}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  perplexica:
    image: itzcrazykns1337/perplexica:main-sha
    container_name: perplexica
    ports:
      - "8080:8080"
    environment:
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}
      - ROCM_VISIBLE_DEVICES=${ROCM_VISIBLE_DEVICES:-}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama_data:
  open-webui_data:
  stable-diffusion_data:
  perplexica_data:

networks:
  default:
    external:
      name: homelab-network