#!/bin/bash

# Deployment script for Media Stack
# Generated by AI (claude-opus-4-6, GPT-5.3 Codex)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_DIR="$SCRIPT_DIR/../manifests/media"

echo "=== Deploying Media Stack ==="
echo ""

# Check prerequisites
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed"
    exit 1
fi

if ! command -v docker compose &> /dev/null; then
    echo "❌ Docker Compose v2 required"
    exit 1
fi

# Create directories
mkdir -p "$MANIFEST_DIR/jellyfin/config"
mkdir -p "$MANIFEST_DIR/sonarr/config"
mkdir -p "$MANIFEST_DIR/radarr/config"
mkdir -p "$MANIFEST_DIR/prowlarr/config"
mkdir -p "$MANIFEST_DIR/qbittorrent/config"
mkdir -p "$MANIFEST_DIR/jellyseerr/config"
mkdir -p "$MANIFEST_DIR/../data/media"

# Set environment file
ENV_FILE="$SCRIPT_DIR/../.env.media"
if [ ! -f "$ENV_FILE" ]; then
    echo "Creating example .env file..."
    cat > "$ENV_FILE" << EOF
# Media Stack Environment
TZ=Asia/Shanghai
JELLYFIN_PASSWORD=change_this_password
SONARR_PASSWORD=change_this_password
RADARR_PASSWORD=change_this_password
QBITTORRENT_PASSWORD=change_this_password
JELLYSEERR_PASSWORD=change_this_password
EOF
    echo "✅ Created $ENV_FILE (please edit for production)"
fi

# Deploy
echo "🚀 Starting media services..."
cd "$MANIFEST_DIR"
docker compose up -d

# Wait
echo ""
echo "⏳ Waiting for services..."
sleep 15

# Check
echo ""
echo "📊 Service Status:"
docker compose ps

echo ""
echo "✅ Media Stack deployed!"
echo ""
echo "Access points:"
echo "  Jellyfin:   http://localhost:8096"
echo "  Sonarr:     http://localhost:8989"
echo "  Radarr:     http://localhost:7878"
echo "  Prowlarr:   http://localhost:9696"
echo "  qBittorrent: http://localhost:8080"
echo "  Jellyseerr: http://localhost:5055"
echo ""
echo "Next steps:"
echo "  1. Configure reverse proxy (Traefik) for HTTPS"
echo "  2. Set up indexers in Prowlarr"
echo "  3. Add download clients to Sonarr/Radarr"
echo "  4. Configure media folders and permissions"
echo "  5. Enable hardware acceleration in Jellyfin if GPU available"
echo ""
