#!/bin/bash

# Deployment script for Observability Stack
# Generated by AI (claude-opus-4-6, GPT-5.3 Codex)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_DIR="$SCRIPT_DIR/../manifests/observability"

echo "=== Deploying Observability Stack ==="
echo ""

# Check prerequisites
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed"
    exit 1
fi

if ! command -v docker compose &> /dev/null; then
    echo "❌ Docker Compose v2 required"
    exit 1
fi

# Create directories if not exist
mkdir -p "$MANIFEST_DIR/prometheus/rules"
mkdir -p "$MANIFEST_DIR/grafana/provisioning/datasources"
mkdir -p "$MANIFEST_DIR/loki/config"
mkdir -p "$MANIFEST_DIR/tempo/config"
mkdir -p "$MANIFEST_DIR/alertmanager/config"
mkdir -p "$MANIFEST_DIR/uptime-kuma/data"

# Copy configs (if not already present)
if [ ! -f "$MANIFEST_DIR/prometheus/prometheus.yml" ]; then
    echo "⚠️  Prometheus config missing, generating..."
    # Generate with AI would happen here
fi

# Set environment file
ENV_FILE="$SCRIPT_DIR/../.env.observability"
if [ ! -f "$ENV_FILE" ]; then
    echo "Creating example .env file..."
    cat > "$ENV_FILE" << EOF
# Observability Stack Environment
GRAFANA_PASSWORD=admin123
NODE_EXPORTER_ENABLED=true
EOF
    echo "✅ Created $ENV_FILE (please edit for production)"
fi

# Deploy
echo "🚀 Starting services..."
cd "$MANIFEST_DIR"
docker compose up -d

# Wait for health
echo ""
echo "⏳ Waiting for services to be healthy..."
sleep 10

# Check status
echo ""
echo "📊 Service Status:"
docker compose ps

echo ""
echo "✅ Observability Stack deployed!"
echo ""
echo "Access points:"
echo "  Grafana:  http://localhost:3000 (admin/admin123)"
echo "  Prometheus: http://localhost:9090"
echo "  Loki:      http://localhost:3100"
echo "  Tempo:     http://localhost:3200"
echo "  Alerts:    http://localhost:9093"
echo "  Uptime:    http://localhost:3001"
echo ""
echo "Next steps:"
echo "  1. Import Grafana dashboards (see provisioning)"
echo "  2. Configure Prometheus rules in /etc/prometheus/rules"
echo "  3. Set up Alertmanager receivers"
echo "  4. Configure exporters on target nodes"
echo ""
