#!/bin/bash
set -e

# Database initialization script for multi-tenant PostgreSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="$POSTGRES_DB" <<EOF

-- Create databases and users for each service
CREATE DATABASE nextcloud;
CREATE USER nextcloud WITH ENCRYPTED PASSWORD '$NEXTCLOUD_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE nextcloud TO nextcloud;

CREATE DATABASE gitea;
CREATE USER gitea WITH ENCRYPTED PASSWORD '$GITEA_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE gitea TO gitea;

CREATE DATABASE outline;
CREATE USER outline WITH ENCRYPTED PASSWORD '$OUTLINE_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE outline TO outline;

CREATE DATABASE authentik;
CREATE USER authentik WITH ENCRYPTED PASSWORD '$AUTHENTIK_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE authentik TO authentik;

CREATE DATABASE grafana;
CREATE USER grafana WITH ENCRYPTED PASSWORD '$GRAFANA_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE grafana TO grafana;

EOF
