#!/usr/bin/env bash
# =============================================================================
# CN Mirror Setup — Configure Docker and apt sources for China network
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()  { echo -e "\n${BLUE}[STEP]${NC} $*"; }

# Mirror configuration
DOCKER_MIRRORS=(
  "https://docker.m.daocloud.io"
  "https://docker.1ms.run"
  "https://docker.awsl9527.cn"
  "https://docker.hlyun.org"
)

APT_MIRRORS=(
  "mirrors.aliyun.com"
  "mirrors.huaweicloud.com"
  "mirrors.tuna.tsinghua.edu.cn"
  "mirrors.ustc.edu.cn"
)

# Detect if running in China
detect_cn_network() {
  log_step "Detecting network environment..."
  
  # Method 1: Check timezone
  if [[ "$(timedatectl show --property=Timezone --value 2>/dev/null || echo 'Unknown')" == *"Asia/Shanghai"* ]]; then
    log_info "Timezone suggests CN environment"
    return 0
  fi
  
  # Method 2: Try to reach CN-specific services
  if curl -sf --connect-timeout 2 --max-time 3 "https://www.baidu.com" &>/dev/null; then
    log_info "Can reach Baidu - likely CN network"
    return 0
  fi
  
  # Method 3: Check if GitHub is slow/blocked
  if ! curl -sf --connect-timeout 5 --max-time 10 "https://github.com" &>/dev/null; then
    log_warn "Cannot reach GitHub - likely CN network with firewall"
    return 0
  fi
  
  log_info "Network appears to be non-CN"
  return 1
}

# Configure Docker daemon mirrors
configure_docker_mirrors() {
  log_step "Configuring Docker registry mirrors..."
  
  local daemon_json="/etc/docker/daemon.json"
  local backup="${daemon_json}.backup.$(date +%s)"
  
  # Check if Docker is installed
  if ! command -v docker &>/dev/null; then
    log_error "Docker is not installed"
    return 1
  fi
  
  # Backup existing config
  if [[ -f "$daemon_json" ]]; then
    sudo cp "$daemon_json" "$backup"
    log_info "Backed up existing config to $backup"
  fi
  
  # Create new config with mirrors
  local mirrors_json
  mirrors_json=$(printf '%s\n' "${DOCKER_MIRRORS[@]}" | jq -R . | jq -s .)
  
  local new_config
  if [[ -f "$daemon_json" ]]; then
    # Merge with existing config
    new_config=$(jq ". + {\"registry-mirrors\": $mirrors_json}" "$daemon_json" 2>/dev/null || echo "{}")
  else
    new_config="{\"registry-mirrors\": $mirrors_json}"
  fi
  
  echo "$new_config" | sudo tee "$daemon_json" > /dev/null
  log_info "Updated $daemon_json with CN mirrors"
  
  # Restart Docker daemon
  log_info "Restarting Docker daemon..."
  if sudo systemctl restart docker; then
    log_info "Docker restarted successfully"
  else
    log_error "Failed to restart Docker"
    return 1
  fi
  
  # Verify mirrors are active
  sleep 2
  if docker info 2>/dev/null | grep -A 5 "Registry Mirrors:"; then
    log_info "Registry mirrors configured successfully"
  else
    log_warn "Could not verify mirror configuration"
  fi
}

# Configure apt sources for Ubuntu/Debian
configure_apt_mirrors() {
  log_step "Configuring apt sources..."
  
  if [[ ! -f /etc/lsb-release ]]; then
    log_warn "Not Ubuntu/Debian, skipping apt configuration"
    return 0
  fi
  
  source /etc/lsb-release 2>/dev/null || true
  local distro="${DISTRIB_CODENAME:-focal}"
  
  # Detect fastest mirror
  local fastest_mirror=""
  log_info "Testing apt mirror speeds..."
  
  for mirror in "${APT_MIRRORS[@]}"; do
    local start_time=$(date +%s%N)
    if curl -sf --connect-timeout 2 --max-time 3 "https://$mirror" &>/dev/null; then
      local end_time=$(date +%s%N)
      local duration=$(( (end_time - start_time) / 1000000 ))
      log_info "  $mirror: ${duration}ms"
      
      if [[ -z "$fastest_mirror" ]] || [[ $duration -lt ${fastest_duration:-999999} ]]; then
        fastest_mirror="$mirror"
        fastest_duration=$duration
      fi
    fi
  done
  
  if [[ -z "$fastest_mirror" ]]; then
    log_error "No apt mirrors reachable"
    return 1
  fi
  
  log_info "Fastest mirror: $fastest_mirror"
  
  # Backup and update sources.list
  local sources_file="/etc/apt/sources.list"
  local backup="${sources_file}.backup.$(date +%s)"
  
  if [[ -f "$sources_file" ]]; then
    sudo cp "$sources_file" "$backup"
    log_info "Backed up $sources_file to $backup"
  fi
  
  # Generate new sources.list
  cat <<EOF | sudo tee "$sources_file" > /dev/null
# CN Mirror: $fastest_mirror
# Generated by homelab-stack setup-cn-mirrors.sh

deb https://$fastest_mirror/ubuntu/ $distro main restricted universe multiverse
deb https://$fastest_mirror/ubuntu/ $distro-updates main restricted universe multiverse
deb https://$fastest_mirror/ubuntu/ $distro-backports main restricted universe multiverse
deb https://$fastest_mirror/ubuntu/ $distro-security main restricted universe multiverse
EOF
  
  log_info "Updated $sources_file"
  
  # Update package lists
  log_info "Running apt update..."
  sudo apt update -qq
}

# Configure pip mirrors (optional)
configure_pip_mirrors() {
  log_step "Configuring pip mirrors..."
  
  local pip_conf="$HOME/.pip/pip.conf"
  mkdir -p "$(dirname "$pip_conf")"
  
  cat > "$pip_conf" <<EOF
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
trusted-host = pypi.tuna.tsinghua.edu.cn
EOF
  
  log_info "Created $pip_conf"
}

# Configure npm mirrors (optional)
configure_npm_mirrors() {
  log_step "Configuring npm mirrors..."
  
  if command -v npm &>/dev/null; then
    npm config set registry https://registry.npmmirror.com
    log_info "Configured npm to use npmmirror.com"
  else
    log_warn "npm not found, skipping"
  fi
}

# Main execution
main() {
  echo -e "${BLUE}=== HomeLab Stack — CN Mirror Configuration ===${NC}\n"
  
  # Check if running as root or with sudo
  if [[ $EUID -eq 0 ]]; then
    log_warn "Running as root is not recommended"
  fi
  
  # Detect CN network
  if ! detect_cn_network; then
    echo ""
    read -p "CN network not detected. Configure mirrors anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      log_info "Aborted"
      exit 0
    fi
  fi
  
  echo ""
  log_info "Configuring CN mirrors..."
  
  # Docker mirrors (requires sudo)
  if [[ $EUID -ne 0 ]]; then
    echo ""
    read -p "Configure Docker registry mirrors? (requires sudo) (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
      configure_docker_mirrors
    fi
  else
    configure_docker_mirrors
  fi
  
  # apt mirrors (requires sudo)
  if [[ $EUID -ne 0 ]]; then
    echo ""
    read -p "Configure apt sources? (requires sudo) (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
      configure_apt_mirrors
    fi
  else
    configure_apt_mirrors
  fi
  
  # pip mirrors (optional)
  echo ""
  read -p "Configure pip mirrors (Python)? (y/N): " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    configure_pip_mirrors
  fi
  
  # npm mirrors (optional)
  echo ""
  read -p "Configure npm mirrors (Node.js)? (y/N): " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    configure_npm_mirrors
  fi
  
  echo ""
  log_info "${GREEN}✓ CN mirror configuration complete!${NC}"
  log_info ""
  log_info "Next steps:"
  log_info "  1. Run ./scripts/cn-pull.sh --stack <name> to pull images with acceleration"
  log_info "  2. Run ./install.sh to continue with installation"
}

# Run main
main "$@"
