#!/usr/bin/env bash
# =============================================================================
# Package Manager Mirror Setup for CN Networks
# Configures apt (Ubuntu/Debian) and apk (Alpine) to use Chinese mirrors
# =============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Backup directory
BACKUP_DIR="/tmp/pkg-mirror-backup-$(date +%Y%m%d_%H%M%S)"

# =============================================================================
# Ubuntu/Debian APT Mirror Setup
# =============================================================================
setup_ubuntu_mirrors() {
  log_info "检测到 Ubuntu/Debian 系统"
  
  if [[ $EUID -ne 0 ]]; then
    log_error "需要 root 权限来修改 apt 源"
    return 1
  fi
  
  # Detect Ubuntu version
  local codename
  codename=$(lsb_release -cs 2>/dev/null || grep "VERSION_CODENAME" /etc/os-release | cut -d= -f2)
  
  if [[ -z "$codename" ]]; then
    log_error "无法检测 Ubuntu 版本"
    return 1
  fi
  
  log_info "系统版本: $codename"
  
  # Backup original sources.list
  if [[ -f "/etc/apt/sources.list" ]]; then
    mkdir -p "$BACKUP_DIR"
    cp /etc/apt/sources.list "$BACKUP_DIR/sources.list"
    log_info "已备份原始配置到: $BACKUP_DIR/sources.list"
  fi
  
  # Backup sources.list.d
  if [[ -d "/etc/apt/sources.list.d" ]]; then
    cp -r /etc/apt/sources.list.d "$BACKUP_DIR/"
    log_info "已备份 sources.list.d 目录"
  fi
  
  # Generate new sources.list with TUNA mirror (清华源)
  cat > /etc/apt/sources.list <<EOF
# 清华大学开源软件镜像站
# ${codename} - Generated by homelab-stack setup

deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename} main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename}-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename}-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename}-security main restricted universe multiverse

# 预发布软件源（可选）
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename}-proposed main restricted universe multiverse
EOF
  
  log_info "已写入清华源配置到 /etc/apt/sources.list"
  
  # Alternative mirrors (can be swapped)
  cat > /etc/apt/sources.list.available-mirrors <<'EOF'
# Available Chinese mirrors for Ubuntu/Debian
# Uncomment and replace in sources.list as needed

# 清华大学 TUNA (推荐)
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename} main restricted universe multiverse

# 阿里云
# deb https://mirrors.aliyun.com/ubuntu/ ${codename} main restricted universe multiverse

# 中科大 USTC
# deb https://mirrors.ustc.edu.cn/ubuntu/ ${codename} main restricted universe multiverse

# 网易
# deb https://mirrors.163.com/ubuntu/ ${codename} main restricted universe multiverse

# 华为云
# deb https://mirrors.huaweicloud.com/ubuntu/ ${codename} main restricted universe multiverse
EOF
  
  log_info "已创建备用镜像列表: /etc/apt/sources.list.available-mirrors"
  
  # Update package index
  log_info "正在更新软件包索引..."
  if apt-get update; then
    log_info "软件包索引更新成功 ✓"
  else
    log_warn "软件包索引更新失败，请检查网络连接"
  fi
}

# =============================================================================
# Alpine APK Mirror Setup
# =============================================================================
setup_alpine_mirrors() {
  log_info "检测到 Alpine Linux 系统"
  
  if [[ $EUID -ne 0 ]]; then
    log_error "需要 root 权限来修改 apk 源"
    return 1
  fi
  
  # Detect Alpine version
  local version
  version=$(grep "VERSION_ID" /etc/os-release | cut -d= -f2 | tr -d '"')
  local major_minor
  major_minor=$(echo "$version" | cut -d. -f1,2)
  
  log_info "Alpine 版本: $version"
  
  # Backup original repositories
  if [[ -f "/etc/apk/repositories" ]]; then
    mkdir -p "$BACKUP_DIR"
    cp /etc/apk/repositories "$BACKUP_DIR/repositories"
    log_info "已备份原始配置到: $BACKUP_DIR/repositories"
  fi
  
  # Generate new repositories with USTC mirror (中科大)
  cat > /etc/apk/repositories <<EOF
# 中科大开源镜像站
# Alpine ${major_minor}

https://mirrors.ustc.edu.cn/alpine/v${major_minor}/main
https://mirrors.ustc.edu.cn/alpine/v${major_minor}/community

# 测试分支（可选）
# https://mirrors.ustc.edu.cn/alpine/edge/testing
EOF
  
  log_info "已写入中科大源配置到 /etc/apk/repositories"
  
  # Alternative mirrors
  cat > /etc/apk/repositories.available-mirrors <<EOF
# Available Chinese mirrors for Alpine Linux
# Uncomment and replace in repositories as needed

# 中科大 USTC (推荐)
# https://mirrors.ustc.edu.cn/alpine/v${major_minor}/main
# https://mirrors.ustc.edu.cn/alpine/v${major_minor}/community

# 清华大学 TUNA
# https://mirrors.tuna.tsinghua.edu.cn/alpine/v${major_minor}/main
# https://mirrors.tuna.tsinghua.edu.cn/alpine/v${major_minor}/community

# 阿里云
# https://mirrors.aliyun.com/alpine/v${major_minor}/main
# https://mirrors.aliyun.com/alpine/v${major_minor}/community
EOF
  
  log_info "已创建备用镜像列表: /etc/apk/repositories.available-mirrors"
  
  # Update package index
  log_info "正在更新软件包索引..."
  if apk update; then
    log_info "软件包索引更新成功 ✓"
  else
    log_warn "软件包索引更新失败，请检查网络连接"
  fi
}

# =============================================================================
# Debian APT Mirror Setup
# =============================================================================
setup_debian_mirrors() {
  log_info "检测到 Debian 系统"
  
  if [[ $EUID -ne 0 ]]; then
    log_error "需要 root 权限来修改 apt 源"
    return 1
  fi
  
  # Detect Debian version
  local codename
  codename=$(lsb_release -cs 2>/dev/null || grep "VERSION_CODENAME" /etc/os-release | cut -d= -f2)
  
  if [[ -z "$codename" ]]; then
    log_error "无法检测 Debian 版本"
    return 1
  fi
  
  log_info "系统版本: $codename"
  
  # Backup original sources.list
  if [[ -f "/etc/apt/sources.list" ]]; then
    mkdir -p "$BACKUP_DIR"
    cp /etc/apt/sources.list "$BACKUP_DIR/sources.list"
    log_info "已备份原始配置到: $BACKUP_DIR/sources.list"
  fi
  
  # Generate new sources.list with USTC mirror
  cat > /etc/apt/sources.list <<EOF
# 中科大开源镜像站
# Debian ${codename}

deb https://mirrors.ustc.edu.cn/debian/ ${codename} main contrib non-free non-free-firmware
deb https://mirrors.ustc.edu.cn/debian/ ${codename}-updates main contrib non-free non-free-firmware
deb https://mirrors.ustc.edu.cn/debian-security/ ${codename}-security main contrib non-free non-free-firmware

# Backports（可选）
# deb https://mirrors.ustc.edu.cn/debian/ ${codename}-backports main contrib non-free non-free-firmware
EOF
  
  log_info "已写入中科大源配置到 /etc/apt/sources.list"
  
  # Update package index
  log_info "正在更新软件包索引..."
  if apt-get update; then
    log_info "软件包索引更新成功 ✓"
  else
    log_warn "软件包索引更新失败，请检查网络连接"
  fi
}

# =============================================================================
# Restore original mirrors
# =============================================================================
restore_mirrors() {
  log_info "恢复原始镜像源配置..."
  
  # Find the most recent backup
  local latest_backup
  latest_backup=$(ls -dt /tmp/pkg-mirror-backup-* 2>/dev/null | head -1)
  
  if [[ -z "$latest_backup" ]]; then
    log_error "未找到备份文件"
    return 1
  fi
  
  log_info "使用备份: $latest_backup"
  
  # Restore based on system type
  if [[ -f "$latest_backup/sources.list" ]]; then
    cp "$latest_backup/sources.list" /etc/apt/sources.list
    log_info "已恢复 /etc/apt/sources.list"
  fi
  
  if [[ -d "$latest_backup/sources.list.d" ]]; then
    rm -rf /etc/apt/sources.list.d
    cp -r "$latest_backup/sources.list.d" /etc/apt/
    log_info "已恢复 sources.list.d 目录"
  fi
  
  if [[ -f "$latest_backup/repositories" ]]; then
    cp "$latest_backup/repositories" /etc/apk/repositories
    log_info "已恢复 /etc/apk/repositories"
  fi
  
  log_info "恢复完成 ✓"
}

# =============================================================================
# Main
# =============================================================================
usage() {
  cat <<EOF
用法:
  $0 [选项]

选项:
  --setup     配置国内镜像源（默认）
  --restore   恢复原始镜像源
  --help      显示帮助信息

支持的系统:
  - Ubuntu/Debian (apt)
  - Alpine Linux (apk)

示例:
  sudo $0 --setup
  sudo $0 --restore

注意:
  此脚本需要 root 权限运行
EOF
  exit 0
}

# Parse arguments
ACTION="${1:---setup}"

case "$ACTION" in
  --setup)
    ;;
  --restore)
    restore_mirrors
    exit $?
    ;;
  --help|-h)
    usage
    ;;
  *)
    log_error "未知参数: $ACTION"
    usage
    ;;
esac

# Check root
if [[ $EUID -ne 0 ]]; then
  log_error "此脚本需要 root 权限运行"
  echo "请使用: sudo $0"
  exit 1
fi

# Interactive prompt
echo -e "\n${BOLD}${BLUE}=== 软件包管理器镜像源配置 ===${NC}\n"
read -p "是否在中国大陆部署? (y/N): " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  log_info "已取消配置"
  exit 0
fi

# Detect OS and setup mirrors
if [[ -f "/etc/debian_version" ]]; then
  # Debian
  setup_debian_mirrors
elif [[ -f "/etc/lsb-release" ]] && grep -q "Ubuntu" /etc/lsb-release 2>/dev/null; then
  # Ubuntu
  setup_ubuntu_mirrors
elif [[ -f "/etc/alpine-release" ]]; then
  # Alpine
  setup_alpine_mirrors
else
  log_error "不支持的操作系统"
  log_info "仅支持: Ubuntu, Debian, Alpine Linux"
  exit 1
fi

echo -e "\n${GREEN}${BOLD}✓ 软件包镜像源配置完成${NC}\n"
echo "备份目录: $BACKUP_DIR"
echo ""
echo "测试安装速度:"
echo "  apt: sudo apt-get install <package>"
echo "  apk: sudo apk add <package>"
echo ""
echo "恢复原配置:"
echo "  sudo $0 --restore"
