tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
    modern:
      minVersion: VersionTLS13

  certificates:
    - domains:
        - main: "${DOMAIN}"
          sans:
            - "*.${DOMAIN}"
