apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    jsonData:
      httpMethod: POST

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      tracesToLogs:
        datasourceUid: loki
        tags: [ 'job', 'instance', 'hostname' ] # Common trace tags to link to logs
        mappedKeys: [ 'traceID' ]
        mapTagNames:
          - { source: 'host.name', target: 'hostname' }
          - { source: 'service.name', target: 'job' }
        spanStartTimeShift: '1h' # Adjust as needed
        spanEndTimeShift: '1h'   # Adjust as needed
      nodeGraph:
        enabled: true
      search:
        hide: false # Show search in Tempo explore
