apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    version: 2
    orgId: 1

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
      derivedFields:
        - datasourceUid: tempo
          matchers:
            - __temp_trace_id
          url: 'http://tempo:3200/trace/${__value}'
          name: 'TraceID'
    version: 1
    orgId: 1

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
      tracesToLogs:
        datasourceUid: loki
        customQuery: true
        query: '{service_name="${__value}"}'
      serviceMap:
        datasourceUid: prometheus
      search:
        hidden: false
    version: 1
    orgId: 1